backend:
  name: github
  repo: solomonschwartz/solomon-schwartz-website  # Your GitHub repository
  branch: main  # Branch where content will be committed

media_folder: "assets/uploads"  # Repo path for uploaded files
public_folder: "/assets/uploads"  # Public URL path for those files

media_library:
  name: file
  config:
    multiple: true

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime", format: "YYYY-MM-DD HH:mm", default: "" }
      - { name: "description", label: "Description", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "videos"
    label: "Videos"
    folder: "_videos"
    create: true
    format: "yaml"
    extension: "yaml"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Video Title", widget: "string" }
      - { name: "url", label: "YouTube URL", widget: "string" }
      - { name: "description", label: "Description", widget: "text", required: false }
